// Code generated by reset generator; DO NOT EDIT.

package models

func (s *Metric) Reset() {
	if s == nil {
		return
	}
	s.ID = ""
	s.MType = ""
	if s.Delta != nil {
		*s.Delta = 0
	}
	if s.Value != nil {
		*s.Value = 0
	}
	s.Hash = ""
}
