// Code generated by reset generator; DO NOT EDIT.

package models

func (s *Metric) Reset() {
	if s == nil {
		return
	}
	s.ID = ""
	s.MType = ""
	if s.Delta != nil {
		if r, ok := any(s.Delta).(interface{ Reset() }); ok {
			r.Reset()
		} else {
			*s.Delta = 0
		}
	}
	if s.Value != nil {
		if r, ok := any(s.Value).(interface{ Reset() }); ok {
			r.Reset()
		} else {
			*s.Value = 0
		}
	}
	s.Hash = ""
}
