package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.LoadSyntax,
		Dir:  ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		panic(err)
	}

	for _, pkg := range pkgs {
		processPackage(pkg)
	}
}

func processPackage(pkg *packages.Package) {
	var out bytes.Buffer

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				// FIX: ищем комментарий и в gen.Doc, и в ts.Doc
				if !hasGenerateResetComment(gen.Doc) && !hasGenerateResetComment(ts.Doc) {
					continue
				}

				generateReset(&out, ts.Name.Name, st, pkg.TypesInfo)
			}
		}
	}

	if out.Len() == 0 {
		return
	}

	writeFile(pkg, out.Bytes())
}

func hasGenerateResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}
func hasResetMethod(t types.Type) bool {
	if m, _, _ := types.LookupFieldOrMethod(
		t,
		true,
		nil,
		"Reset",
	); m != nil {
		return true
	}
	if m, _, _ := types.LookupFieldOrMethod(
		types.NewPointer(t),
		true,
		nil,
		"Reset",
	); m != nil {
		return true
	}
	return false

}

func writeFile(pkg *packages.Package, code []byte) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset generator; DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg.Name + "\n\n")

	buf.Write(code)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	dir := filepath.Dir(pkg.GoFiles[0])
	file := filepath.Join(dir, "reset.gen.go")

	_ = os.WriteFile(file, formatted, 0644)
}

func generateReset(out *bytes.Buffer, structName string, st *ast.StructType, info *types.Info) {
	fmt.Fprintf(out, "func (s *%s) Reset() {\n", structName)
	fmt.Fprintf(out, "\tif s == nil { return }\n")

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		tv, ok := info.Types[field.Type]
		if !ok || tv.Type == nil {
			continue
		}

		t := tv.Type

		switch t.Underlying().(type) {

		case *types.Slice:
			fmt.Fprintf(out,
				"\ts.%s = s.%s[:0]\n",
				name,
				name,
			)

		case *types.Map:
			fmt.Fprintf(out,
				"\tclear(s.%s)\n",
				name,
			)

		case *types.Pointer:
			fmt.Fprintf(out,
				"\tif s.%s != nil {\n",
				name,
			)

			fmt.Fprintf(out,
				"\t\tif r, ok := any(s.%s).(interface{ Reset() }); ok {\n",
				name,
			)
			fmt.Fprintf(out, "\t\t\tr.Reset()\n")
			fmt.Fprintf(out, "\t\t} else {\n")

			ptr := t.(*types.Pointer)

			fmt.Fprintf(out,
				"\t\t\t*s.%s = %s\n",
				name,
				zeroValue(ptr.Elem()),
			)

			fmt.Fprintf(out, "\t\t}\n")
			fmt.Fprintf(out, "\t}\n")

		default:
			if hasResetMethod(t) {
				fmt.Fprintf(out,
					"\ts.%s.Reset()\n",
					name,
				)
				continue
			}
			fmt.Fprintf(out,
				"\ts.%s = %s\n",
				name,
				zeroValue(t),
			)
		}
	}

	fmt.Fprintf(out, "}\n\n")
}

func zeroValue(t types.Type) string {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.String:
			return `""`
		case types.Bool:
			return "false"
		default:
			return "0"
		}
	case *types.Pointer:
		return "nil"
	case *types.Slice:
		return "nil"
	case *types.Map:
		return "nil"
	default:
		return types.TypeString(t, nil) + "{}"
	}
}
