package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	cfg := &packages.Config{
		Mode: packages.LoadSyntax,
		Dir:  ".",
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}
	for _, pkg := range pkgs {
		if err := processPackage(pkg); err != nil {
			return err
		}
	}
	return nil
}

func processPackage(pkg *packages.Package) error {
	var out bytes.Buffer

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if !hasGenerateResetComment(gen.Doc) && !hasGenerateResetComment(ts.Doc) {
					continue
				}

				generateReset(&out, ts.Name.Name, st, pkg.TypesInfo)
			}
		}
	}

	if out.Len() == 0 {

		return nil
	}
	return writeFile(pkg, out.Bytes())
}

func hasGenerateResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}

func hasResetMethod(t types.Type) bool {
	m, _, _ := types.LookupFieldOrMethod(
		types.NewPointer(t),
		true,
		nil,
		"Reset",
	)
	return m != nil
}

func writeFile(pkg *packages.Package, code []byte) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by reset generator; DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg.Name + "\n\n")
	buf.Write(code)
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated code: %w", err)
	}
	dir := filepath.Dir(pkg.GoFiles[0])
	file := filepath.Join(dir, "reset.gen.go")
	if err := os.WriteFile(file, formatted, 0644); err != nil {
		return fmt.Errorf("write file %s: %w", file, err)
	}
	return nil
}

func generateReset(out *bytes.Buffer, structName string, st *ast.StructType, info *types.Info) {
	fmt.Fprintf(out, "func (s *%s) Reset() {\n", structName)
	fmt.Fprintf(out, "\tif s == nil { return }\n")

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		tv, ok := info.Types[field.Type]
		if !ok || tv.Type == nil {
			continue
		}

		t := tv.Type

		switch t.Underlying().(type) {

		case *types.Slice:
			fmt.Fprintf(out,
				"\ts.%s = s.%s[:0]\n",
				name,
				name,
			)

		case *types.Map:
			fmt.Fprintf(out,
				"\tclear(s.%s)\n",
				name,
			)

		case *types.Pointer:
			ptr := t.(*types.Pointer)
			fmt.Fprintf(out, "\tif s.%s != nil {\n", name)

			if hasResetMethod(ptr.Elem()) {
				fmt.Fprintf(out, "\t\ts.%s.Reset()\n", name)
			} else {
				fmt.Fprintf(out,
					"\t\t*s.%s = %s\n",
					name,
					zeroValue(ptr.Elem()),
				)
			}
			fmt.Fprintf(out, "\t}\n")
		default:
			if hasResetMethod(t) {
				fmt.Fprintf(out,
					"\ts.%s.Reset()\n",
					name,
				)
				continue
			}
			fmt.Fprintf(out,
				"\ts.%s = %s\n",
				name,
				zeroValue(t),
			)
		}
	}

	fmt.Fprintf(out, "}\n\n")
}

func zeroValue(t types.Type) string {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch u.Kind() {
		case types.String:
			return `""`
		case types.Bool:
			return "false"
		default:
			return "0"
		}
	case *types.Pointer:
		return "nil"
	case *types.Slice:
		return "nil"
	case *types.Map:
		return "nil"
	default:
		return types.TypeString(t, nil) + "{}"
	}
}
